services:
  - type: web
    name: cbo-backend-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn educate_us_rise_us.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "false"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.8"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cbo-backend-db
          property: connectionString

databases:
  - name: cbo-backend-db
    plan: free
